owner: jae1911
repo: status.777.tf
assignees: jae1911
user-agent: jae1911

sites:
  - name: Main Website
    url: https://777.tf
  - name: DN0 Social
    url: https://soc.jae.fi
  - name: Noiseless Storage (EU-FI)
    url: $NSSTORAGE_URI
  - name: Vaultwarden
    url: $VWARDEN_URI
  - name: Public Image CDN
    url: https://i.j4.lc
  - name: Public General CDN
    url: https://bm.777.tf

status-website:
  cname: status.777.tf
  logoUrl: https://bm.jae.fi/Logo-abs.svg
  name: JAE Status
  introTitle: "JAE Status"
  theme: night
  introMessage: Status of the [public services](https://777.tf).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
