owner: jae1911
repo: status.jae.fi
assignees: jae1911
user-agent: jae1911

sites:
  - name: Piped (Frontend)
    url: https://yt.jae.fi
  - name: Piped (API)
    url: https://api.yt.jae.fi
  - name: Piped (Proxy)
    url: https://px.yt.jae.fi
  - name: LibReddit
    url: https://rd.jae.su
  - name: Nitter
    url: https://twitter.jae.su
  - name: PrivateBin
    url: https://bin.jae.fi
  - name: Reddit Account Search
    url: https://reddit.jae.su
  - name: KeyOxide
    url: https://keys.jae.fi
  - name: ProxiTok
    url: https://tok.jae.fi
  - name: SearXNG
    url: https://search.jae.fi
  - name: Wikiless
    url: https://wiki.jae.fi
  - name: Rimgo
    url: https://imgur.jae.fi
  - name: Excalidraw
    url: https://draw.jae.fi
  - name: Hydrogen (Matrix client)
    url: https://hydrogen.jae.fi
  - name: UwU Proxified
    url: https://uwu.jae.fi
  - name: LibreTranslate
    url: https://translate.jae.fi
  - name: Main Router
    check: "tcp-ping"
    url: $MAINROUTERIP
    port: $MAINROUTERPORT

status-website:
  cname: status.jae.fi
  logoUrl: https://bm.jae.fi/Logo-abs.svg
  name: JAE Status
  introTitle: "JAE Status"
  theme: night
  introMessage: Status of the [public services](https://library.jae.fi/doku.php?id=int:instances).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
